### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by nawrattel** [hjamesw93/wallboarder#3]
Would be nice to have an auto refresh feature, with configurable interval/s

**Comment by hjmsw** [comment]
Auto refresh feature has been implemented and currently present in develop branch - This feature will be included with 0.2.0.

**Comment by hjmsw** [comment]
@nawrattel Wallboarder 0.3.0 includes a feature for auto reloading the page when a wallboard is saved from elsewhere (via socket.io) - Removing the need for a configurable auto refresh as far as I can see.

Configurable auto refresh has now been removed.
